INSERT INTO user(USER_ID, LOGIN, PASSWORD, FIRST_NAME, LAST_NAME, PHONE, EMAIL, GENDER)
  VALUES (RANDOM_UUID(), 'asda', 'sda', 'sdas', 'dasda', 'dad', 'dsad', 'MALE');
INSERT INTO user(USER_ID, LOGIN, PASSWORD, FIRST_NAME, LAST_NAME, PHONE, EMAIL, GENDER)
  VALUES (RANDOM_UUID(), 'asadsda', 'da', 'qw', 'eq', 'cxz', 'fdf', 'FEMALE');
INSERT INTO user(USER_ID, LOGIN, PASSWORD, FIRST_NAME, LAST_NAME, PHONE, EMAIL, GENDER)
  VALUES ('f9a5ae5f-1554-4527-b822-53e41da1f450', 'f', 'as', 'qw', 'vcv', 'fd', 'asda', 'MALE');


INSERT INTO product(PRODUCT_ID, TITLE, PRICE, USER_ID)
  VALUES (RANDOM_UUID(), 'asda', 4440, 'f9a5ae5f-1554-4527-b822-53e41da1f450');
INSERT INTO product(PRODUCT_ID, TITLE, PRICE, USER_ID)
  VALUES (RANDOM_UUID(), 'qqdqd', 223, 'f9a5ae5f-1554-4527-b822-53e41da1f450');